###########
# site.url, site.title

url:   'https://calltracker.io'
title: 'calltracker.io'
name: 'Calltracker'

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

gems:
  - jekyll-sitemap

exclude:
- README.md


safe: true
lsi: false

# Compress html
compress_html:
  clippings: ['!--', html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]

